// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Barang struct {
	ID          int    `json:"id"`
	Nama        string `json:"nama"`
	Description string `json:"description"`
}

type JenisBarang struct {
	ID              int    `json:"id"`
	NamaJenisBarang string `json:"namaJenisBarang"`
}

type Karyawan struct {
	ID         int    `json:"id"`
	IDKaryawan string `json:"idKaryawan"`
	Nama       string `json:"nama"`
	Email      string `json:"email"`
	NoHp       string `json:"noHp"`
}
